### ISSUE TITLE
How to properly create the NewRelicApplication instead of the default CWebApplication

### ISSUE THREAD

**Issue by ptheofan** [gtcode/yii-newrelic#5]
Hi, a better (more Yii compliant) way to instantiate the NewRelicApplication in place of the default CWebApplication would be to create your own `class Yii extends YiiBase` as described also in the yii.php file and from there overload the `createWebApplication`

``` php
    public static function createWebApplication($config=null)
    {
        return self::createApplication('NewRelicApplication',$config);
    }
```

As described in Yii, the right way to encapsulate Yii

``` php
/**
 * Yii is a helper class serving common framework functionalities.
 *
 * It encapsulates {@link YiiBase} which provides the actual implementation.
 * By writing your own Yii class, you can customize some functionalities of YiiBase.
 *
 * @author Qiang Xue <qiang.xue@gmail.com>
 * @package system
 * @since 1.0
 */
class Yii extends YiiBase
{
}
```

Hope this provides some insight in "customising" Yii the way it was meant to.

and thanks for the ext. Just trying it... really nice :)

**Comment by gtcode** [comment]
Great, thanks for finding this.  Do you have time to link to documentation on properly encapsulating Yii?  Just so I can check it over.  And if you have time, can you do a PR?

**Comment by firecentaur** [comment]
Can you please give an example of the class you say to create? class NewRelicApplication extends CApplicationComponent.

I am getting Fatal error: Class 'CApplicationComponent' not found in NewRelicApplication.php on line 21

**Comment by gtcode** [comment]
Just speculating, but you probably do not need this extension any longer, since New Relic's PHP API should be sufficiently evolved by now.
