### ISSUE TITLE
hi there, I keep getting Warning: include(): Failed opening 'NewRelicApplication.php' f

### ISSUE THREAD

**Issue by firecentaur** [gtcode/yii-newrelic#9]
how can I include this file?

**Comment by firecentaur** [comment]
If I include it in my index.php I get 'newrelic' already loaded...

**Comment by gtcode** [comment]
Thanks for responding.  This extension is WAY out of date and you should not need to use it with Yii and New Relic at this point.  Please contact New Relic support for assistance with integrating New Relic into your Yii 1.0 application.
